version: '3'
services:
  # Docker in Docker images for test
  dind:
    container_name: dind-test # name of the container
    image: docker:dind
    restart: "always"
    networks: # bridge
      - dind-network
    volumes: # certificate
      - some-docker-certs-ca:/certs/ca
      - some-docker-certs-client:/certs/client
    environment: # this behavior is enabled by default
      - DOCKER_TLS_CERTDIR=/certs
    privileged: true

networks:
  dind-network:
    driver: bridge
volumes: # local volume
  some-docker-certs-ca:
    external: true
  some-docker-certs-client:
    external: true
