#####################################################
# Creation of three DinD for Docker Swarm
#
#
# This Docker Compose file allows to create three
# DinD (Docker in Docker) containers in the same network,
# it is a good idea for Swarm test
#
#
# Author: quaktuss
# Date of creation: 01/08/2023
# Last update : 08/08/2023
# GitHub Repository : https://github.com/quaktuss/docker-swarm-project
#####################################################

version: '3'
services:
  docker:
    image: docker:dind
    networks:
      - dind-network
    # Inside the directory specified by environment, certificate file will
    # create ( *.pem)
    volumes:
      - certs-ca:/certs/ca
      - certs-client:/certs/client
    # Always restart the container if exits with a non-zero code
    restart: "on-failure"
    # Privileged true is required for dind to work properly
    privileged: true
    # This behavior is enabled by default since v19.03
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    # Replicate the same container three time
    deploy:
      mode: replicated
      replicas: 3

networks:
  dind-network:
    driver: bridge

# Create local volume for the certificate
# External false will create the volume if not exists
volumes:
  certs-ca:
    external: false
  certs-client:
    external: false
